# fly.toml app configuration file generated for git-code-stats-collector-prod-empty-leaf-8186 on 2024-09-18T21:47:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'git-code-stats-collector-prod-empty-leaf-8186'
primary_region = 'lax'

[build]

[[mounts]]
  source = 'github_stats_data'
  destination = '/data'

[processes]
  app = "python src/scheduler.py 2026-ASU-WiCS-Opportunity-Hack"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
