# fly.toml app configuration file generated for git-code-stats-collector-prod-proud-dew-626 on 2024-09-09T20:36:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'git-code-stats-collector-prod-proud-dew-626'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'github_stats_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
